# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb5367e06b6269aaaa7d156cf945c11af30ddc587e6efa402fb2c9422c54a1517de842afaae8f8dc94985e27d912920072984b5c219695eefae20ac0a62db428

test:
  secret_key_base: 956c0b534a7cfb4de3a1b0397a1b1a4ca8c975fa876d57341015b7abfb5498d10763bfa3cc32f8d9a9f38e9095766bf42e8b263f73e9024a0a3092e14c5fb543

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
